ContractingApp/Models/Contractor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContractingApp.Models
{
    public class Contractor
    {

        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
      
        [ForeignKey("ContractorId")]
        public virtual Address ContractorAddress { get; set; }
        [Required]
        [MaxLength(10)]
        [MinLength(10)]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone Number can be digits only of length 10")]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        [Required]
        public ContractorType Type { get; set; }
        [Display(Name = "Health Status")]
        public HealthStatus HealthStatus { get; set; }
        public bool IsDeleted { get; set; } = false;
       // public ContractorRelations ContractorRelations { get; set; }

        //[InverseProperty("Contractor1")]
        //public virtual ContractorRelations Contractor1Relations { get; set; }
        //[InverseProperty("Contractor2")]
        //public virtual ContractorRelations Contractor2Relations { get; set; }

    }
    public enum ContractorType
    {
        [Display(Name ="Carrier")]
        Carrier,
        [Display(Name = "MGA")]
        MGA,
        [Display(Name = "Advisor")]
        Advisor
    }
    public enum HealthStatus
    {
        [Display(Name = "Green")]
        Green,
        [Display(Name = "Red")]
        Red,
        [Display(Name = "Yellow")]
        Yellow
    }
}

ContractingApp/Controllers/ContractorController.cs
using ContractingApp.Models;
using ContractingApp.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;


namespace ContractingApp.Controllers
{
    public class ContractorController : Controller
    {
        private readonly IContractorService contractService;
        private readonly ILogger<ContractorController> logger;

        public ContractorController(IContractorService contractService, ILogger<ContractorController> logger)
        {
            this.contractService = contractService;
            this.logger = logger;
        }
        public IActionResult Index()
        {
            try
            {
                var contractors = contractService.GetContractors().Result;
                return View(contractors);
            }
            catch (Exception ex)
            {
                logger.LogInformation("An error occured. Please find below the error details.");
                logger.LogError("Stack Trace {0}", ex.StackTrace);
                logger.LogError("Error Message {0}", ex.Message);
                return RedirectToAction("Index", "Error");
            }
        }
        [HttpPost]
        public IActionResult AddNewContractor(Contractor contractor)
        {
            try
            {
                var numberOfRecords = contractService.AddContractor(contractor);
                if (numberOfRecords > 0)
                {
                    TempData["message"] = "Success";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                logger.LogInformation("An error occured. Please find below the error details.");
                logger.LogError("Stack Trace {0}", ex.StackTrace);
                logger.LogError("Error Message {0}", ex.Message);
                return RedirectToAction("Index", "Error");
            }
        }
        [HttpGet]
        public IActionResult GetContractorDetails(int Id)
        {
            try
            {
                var contractor = contractService.GetContractorDetails(Id).Result;
                return View(contractor);
            }
            catch (Exception ex)
            {
                logger.LogInformation("An error occured. Please find below the error details.");
                logger.LogError("Stack Trace {0}", ex.StackTrace);
                logger.LogError("Error Message {0}", ex.Message);
                return RedirectToAction("Index", "Error");
            }
        }
        [HttpGet]
        public IActionResult AddNewContractor()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                logger.LogInformation("An error occured. Please find below the error details.");
                logger.LogError("Stack Trace {0}", ex.StackTrace);
                logger.LogError("Error Message {0}", ex.Message);
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

ContractingApp/Views/Contractor/AddNewContractor.cshtml
@model ContractingApp.Models.Contractor

@{
    ViewData["Title"] = "Add Contractor";
}

<h3>Add Contractor</h3>
<hr />
<br />
<h4>Contractor Details</h4>

   

<form asp-action="AddNewContractor" id="addnewcontractorform">
    <div class="container-fluid">
        <div class="row">
            <div class ="col-md-6 col-sm-6">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <select asp-for="Type" asp-items="Html.GetEnumSelectList<ContractorType>()" class="form-control"></select>
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
            </div>
            
            <div class ="col-md-6 col-sm-6">
               

                <div class="form-group">
                    <label asp-for="ContractorAddress.StreetNumber" class="control-label"></label>
                    <input asp-for="ContractorAddress.StreetNumber" class="form-control" />
                    <span asp-validation-for="ContractorAddress.StreetNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorAddress.StreetName" class="control-label"></label>
                    <input asp-for="ContractorAddress.StreetName" class="form-control" />
                    <span asp-validation-for="ContractorAddress.StreetName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorAddress.Suite" class="control-label"></label>
                    <input asp-for="ContractorAddress.Suite" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="ContractorAddress.City" class="control-label"></label>
                    <input asp-for="ContractorAddress.City" class="form-control" />
                    <span asp-validation-for="ContractorAddress.City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorAddress.Province" class="control-label"></label>
                    <input asp-for="ContractorAddress.Province" class="form-control" />
                    <span asp-validation-for="ContractorAddress.Province" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorAddress.Country" class="control-label"></label>
                    <input asp-for="ContractorAddress.Country" class="form-control" />
                    <span asp-validation-for="ContractorAddress.Country" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorAddress.PostalCode" class="control-label"></label>
                    <input asp-for="ContractorAddress.PostalCode" class="form-control" />
                    <span asp-validation-for="ContractorAddress.PostalCode" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="addcontractorbutton"/>
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-controller="Contractor" asp-action="Index" id="backtolist">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @if (TempData["message"] != null)
    {
        <script type="text/javascript">
            alert("Contractor added successfully");
        </script>
    }

}

ContractingApp/Views/Contractor/GetContractorDetails.cshtml
@model ContractingApp.Models.Contractor

@{
    ViewData["Title"] = "GetContractorDetails";
}

<h1>Contractor Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HealthStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HealthStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractorAddress.Suite)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContractorAddress.Suite)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractorAddress.StreetNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContractorAddress.StreetNumber)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractorAddress.StreetName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContractorAddress.StreetName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractorAddress.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContractorAddress.City)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractorAddress.Province)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContractorAddress.Province)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractorAddress.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContractorAddress.Country)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContractorAddress.PostalCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContractorAddress.PostalCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" id="backtolist">Back to List</a>
</div>

ContractingApp/Views/Contractor/Index.cshtml
@model IList<ContractingApp.Models.Contractor>

@{
    ViewData["Title"] = "Contractor";
}

<h3>Contractor</h3>


<table class="table" id="contractortable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model[0].PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].HealthStatus)
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HealthStatus)
                </td>
                <td>
                   
                    <a asp-action="GetContractorDetails" asp-route-id="@item.Id">Details</a>
                   
                </td>
            </tr>
        }

    </tbody>
</table>
<p>
    <a asp-action="AddNewContractor" id="addcontractor">Add Contractor</a>
</p>
@*<div id="divSuccessMessage">
    <h2>Successful</h2>
</div>*@
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @if (TempData["message"] != null)
    {
        <script type="text/javascript">
            alert("Contractor added successfully");
           
        </script>
    }
  

    

}